[package]
name = "kfs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[alias]
run = "cargo rustc --release -- --emit=obj && cargo run --release"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
