[unstable]
build-std = ["core"]

[build]
target = "x86_64-unknown-none"

[target.'cfg(target_os = "none")']
runner = "qemu-system-x86_64 -cdrom kfs.iso -boot d -nographic"

[alias]
build-kernel = "rustc --release --no-default-features -- --emit=obj"
build = "build --release"
