name: Adds new issues to the kfs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/kentucky-kried-kernel/projects/2
          github-token: ${{ secrets.TOKEN_GITHUB }}
